config/routes.rb
Rails.application.routes.draw do
  # List articles
  root 'articles#index'

  # Articles routes
  # See: http://jeromedalbert.com/how-dhh-organizes-his-rails-controllers/
  namespace :articles do
    resources :search, only: [:index]
  end
  resources :articles

  # Help routes
  namespace :help do
    resources :markdown, only: [:index]
  end
end

app/models/article.rb
#
# Represent articles of Kip
#
class Article
  include Mongoid::Document
  include Mongoid::Timestamps

  # Average read Time
  WORDS_PER_MINUTE = 310

  # Fields
  field :title
  field :text
  field :author
  field :draft, type: Boolean, default: false
  field :collaborators, type: Array, default: []
  field :number_of_words, type: Integer, default: 0
  field :category, type: String

  # Versions
  # embeds_many :versions, class_name: "ArticleVersion"

  # Indexes
  index({ category: 1 }, unique: false, name: 'category_index')
  index({ author: 1 }, unique: false, name: 'author_index')
  index({ title: 'text', category: 'text', text: 'text', author: 'text' },
        weights: { category: 10, author: 9, title: 8, text: 5 },
        name: 'search_index')

  # Validations
  validates :title, :text, :author, :category, presence: true
  validate :author_not_changed

  # Search a string in Articles
  #
  # @param query [String] String to search
  # @param to_model [boolean] Convert results to model
  # @param limit [Fixnum] Number of results to return
  # @param read_time [boolean] Include read_time when return Array of Hash
  # @return [Array of Hash, Array of Article] Results sort by ratings
  #
  def self.search(query, to_model: false, limit: 15, read_time: false)
    # Perform query
    res = search_query(query, limit)
    # Format results
    if !to_model && read_time
      # Return with read_time
      res.map! do |r|
        r.merge!(read_time: (r[:number_of_words].to_f / WORDS_PER_MINUTE).ceil)
      end
    else
      # Return result
      to_model ? res.map! { |r| new(r) } : res
    end
  end

  # Execute the query to MongoDB
  #
  # @param query [String] String to search
  # @param limit [Fixnum] Number of results to return
  # @return [Array] Array of results
  #
  def self.search_query(query, limit)
    Article.collection
           .find('$text' => { '$search' => query })
           .projection(id: 1, title: 1, category: 1, author: 1,
                       number_of_words: 1, score: { '$meta' => 'textScore' })
           .sort(score: { '$meta' => 'textScore' })
           .limit(limit)
           .entries
  end
  # Make last method private
  private_class_method :search_query

  # Get and approximation of read time per article
  #
  # @return [Integer] minutes to read the article
  #
  def read_time
    (number_of_words.to_f / WORDS_PER_MINUTE).ceil
  end

  private

  # Check if the author as been changed after save.
  def author_not_changed
    return unless author_changed? && persisted?
    errors.add(:author, 'Change of author not allowed!')
  end
end

app/controllers/application_controller.rb
# Base controller for the application
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles/search_controller.rb
#
# Search for articles
#
class Articles::SearchController < ApplicationController
  # Set search
  before_action :set_search

  # Search by an item and return the list of coincidences
  #
  def index
    render json: {
      q: @search,
      results: Article.search(@search, read_time: true)
    }
  end

  private

  # Initialize search var
  #
  def set_search
    @search = params[:q]
  end
end

app/controllers/articles_controller.rb
#
# Articles.
#
class ArticlesController < ApplicationController
  # Set the current article
  before_action :set_article, only: [:edit, :show, :update]
  caches_action :index

  # List all available articles grouped by category.
  #
  def index
    @articles = Article.all.only(:category, :title).asc(:category).asc(:title)
                       .group_by(&:category)
    @count = Article.count
  end

  # Render editor
  #
  def new
    @article = Article.new(title: params[:title])
  end

  # Show an article
  #
  def show
    markdown =
      Redcarpet::Markdown.new(
        Render::Kip, autolink: true, fenced_code_blocks: true, tables: true)
    @text = markdown.render(@article.text).gsub("\n\n", '<br/>').html_safe
  end

  # Edit an article
  #
  def edit; end

  # Update an article
  #
  def update
    @article.assign_attributes(update_article_params)
    # Expire index if its needed
    expire_action(action: :index) if @article.title_changed? ||
                                     @article.category_changed?
    @article.save
    redirect_to @article
  end

  # Store a new article and redirect the user.
  #
  def create
    @article = Article.create(new_article_params)
    if @article.valid?
      # Expire index
      expire_action(action: :index)
      redirect_to @article
    else
      render :new
    end
  end

  private

  # Set the article from params[:id]
  #
  def set_article
    @article = Article.find(params[:id])
  end

  # Article parameters
  #
  def new_article_params
    params.permit(:title, :author, :category, :text, :number_of_words)
  end

  # Article parameters
  #
  def update_article_params
    params.permit(:title, :category, :text, :number_of_words)
  end
end

app/controllers/help/markdown_controller.rb
#
# Help of markdown.
#
class Help::MarkdownController < ApplicationController
  # Cache always index
  caches_action :index

  # Markdown cheatsheet
  #
  def index
    markdown =
      Redcarpet::Markdown.new(
        Render::Kip, autolink: true, fenced_code_blocks: true, tables: true)
    # Load from file
    @cheatsheet =
      markdown.render(markdown_cheatsheet).gsub("\n\n", '<br/>').html_safe
  end

  private

  # Return content of markdown.md
  #
  # @return [String] Content of markdown.md
  #
  def markdown_cheatsheet
    File.read(Rails.root.join('markdown.md'))
  end
end

app/helpers/application_helper.rb
# Base helper of the application
module ApplicationHelper
end

app/helpers/articles_helper.rb
#
# Functions to build interface of Articles
#
module ArticlesHelper
  # Set the HTTP method for Article form
  #
  # @return [Symbol] HTTP method
  #
  def save_method(article)
    article.persisted? ? :patch : :post
  end

  # Add an error to the input when it's needed
  #
  # @param article [Article] Model to check errors
  # @param field [String, Symbol] Field to check the error
  # @return [String] Error or empty string
  #
  def error?(article, field)
    return if article.errors.empty?
    article.errors.messages.keys.include?(field.to_sym) ? 'error' : nil
  end

  # Create a text field for text editor
  #
  # @param article [Article] Article to get the input
  # @param field [Symbol] field to get the input
  # @param placeholder [String] placeholder to display
  # @return [HTML safe string] HTML code of the input
  #
  def text_editor_field(article, field, placeholder)
    text_field_tag field, article.send(field),
                   class: "article-#{field} #{error?(article, field)}",
                   placeholder: placeholder, data: { validate: 'presence' }
  end

  # Sanitize markdown text
  #
  # @param text [Safe String] HTML from markdown article
  # @return [Safe String] HTML without any scripts or dangerous tags
  #
  def sanitize_markdown(text)
    scrubber = Rails::Html::TargetScrubber.new
    scrubber.tags = %w(script style iframe)
    # Sanitize
    sanitize text, scrubber: scrubber
  end

  # Return save button of Article form based on the article status
  # (new or saved)
  #
  # @return [String] Safe String with the button
  #
  def save_button(article)
    text = article.persisted? ? 'Update' : 'Save'
    link_to "#{text} #{material_icon.save.css_class('small')}".html_safe, '',
            class: 'btn btn-light article-save'
  end
end

app/views/application/_footer.html.erb
<footer class="index">
  Made with <%= material_icon.favorite.css_class('small') %> in Seville.
  <%= link_to 'Open Source project.', 'https://github.com/Angelmmiguel/kip', target: '_blank' %>
</footer>

app/views/application/_header.html.erb
<header class="main">
  <div class="wrap">
    <%= link_to root_path, class: 'logo-link' do %>
      <div class="brand">
        <img class="kip" alt="Kip" src="/kip.png"/>
        <h1>Kip</h1>
      </div>
    <% end %>
    <nav class="main">
      <%= yield :navigation_menu %>
    </nav>
  </div>
</header>

app/views/articles/_category.html.erb
<article class="category">
  <h2><%= category %></h2>
  <ul>
    <% articles.each do |article| %>
      <li>
        <h3><%= link_to article.title, article_path(article) %></h3>
      </li>
    <% end %>
  </ul>
</article>

app/views/articles/_form.html.erb
<%= form_tag @article, class: 'articles-form', method: save_method(@article) do %>
  <section class="article article-editor">
    <header>
      <%= text_editor_field @article, :title, 'Insert the title' %>
      <p class="article-credits">
        <% if @article.persisted? %>
          By <%= @article.author %>
        <% else %>
          By <%= text_editor_field @article, :author, 'your name' %>
        <% end %>
        in <%= text_editor_field @article, :category, 'a category' %>
      </p>
    </header>
    <article>
      <%= text_area_tag :text, @article.text, class: "article-text #{error?(@article, :text)}",
            placeholder: "Write here your **#{AwesomeWords.sample}** article.",
            data: { validate: 'presence' } %>
    </article>
  </section>

  <footer class="article-bar">
    <span class="markdown-help hide-on-mobile <%= 'new' if @article.new_record? %>">
      <%= link_to 'Markdown help', help_markdown_index_path, target: '_blank' %>
    </span>
    <%= hidden_field_tag :number_of_words, @article.number_of_words, class: 'article-number' %>
    <span class="word-count">
      <%= material_icon.subject.css_class('small') %>
      <span class="word-count-value"><%= @article.number_of_words %></span> words
    </span>
    <span class="read-time">
      <%= material_icon.timer.css_class('small') %>
      <span class="read-time-value"><%= @article.read_time %></span> min
    </span>
    <span class="save">
      <%= save_button(@article) %>
    </span>
  </footer>

<% end %>

<script>
// Autosize
autosize($('.article-editor textarea'));

// Focus on title if article is new.
// Otherwise, put the cursor at the end of the text.
<% if @article.persisted? %>
  $(".article-text").focus();
<% else %>
  $(".article-title").focus();
<% end %>

</script>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<% content_for :navigation_menu do %>
  <ul class="horizontal">
    <li class="link"><%= link_to material_icon.mode_edit, new_article_path %></li>
  </ul>
<% end %>

<% if @count == 0 %>
  <section class="welcome">
    <h1>Welcome to <span>Kip</span></h1>
    <p>
      Kip is an open source Knowledge base, because <strong>knowledge is Power</strong>.
      Don't let words pass you by, <strong>start to write your awesome first article</strong>.
    </p>
    <%= link_to "Write your first article #{material_icon.mode_edit.css_class('small')}".html_safe,
            new_article_path, class: 'btn btn-blue' %>
  </section>
<% else %>
  <section class="search-box">
    <div class="wrap">
      <article class="search">
        <%= text_field_tag 'search', '', class: 'main-search', placeholder: 'Search' %>
      </article>
    </div>
  </section>

  <div class="wrap">
    <section class="article-list">
      <% @articles.each do |category, articles| %>
        <%= render partial: 'category', locals: { category: category, articles: articles} %>
      <% end %>
    </section>
    <section class="article-search">
    </section>
  </div>

  <%= render partial: 'footer' %>
<% end %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<% content_for :navigation_menu do %>
  <ul class="horizontal">
    <li class="read-time">
      <%= material_icon.timer.css_class('small') %> <%= @article.read_time %> min
    </li>
    <li class="link"><%= link_to material_icon.border_color, edit_article_path(@article) %></li>
  </ul>
<% end %>

<% cache (@article) do %>
  <section class="article article-show">
    <header>
      <h1 class="article-title"><%= strip_tags(@article.title).html_safe %></h1>
      <p class="article-credits">
        By <span><%= strip_tags(@article.author).html_safe %></span> in
        <span><%= strip_tags(@article.category).html_safe %></span>
      </p>
    </header>
    <article class="article-text markdown">
      <%= sanitize_markdown @text %>
    </article>
  </section>

  <%= render partial: 'footer' %>
<% end %>

app/views/help/markdown/index.html.erb
<section class="article article-show">
  <header>
    <h1 class="article-title">Markdown cheatsheet</h1>
  </header>
  <article class="article-text markdown">
    <%= @cheatsheet %>
  </article>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kip</title>
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,300,300italic|Lobster' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Meta tags -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <!-- Favicons -->
  <link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196" />
  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16" />
  <link rel="icon" type="image/png" href="/favicon-128.png" sizes="128x128" />
  <!-- End of favicons -->
</head>
<body>

<%= render partial: 'header' %>

<%= yield %>

</body>
</html>